### PR TITLE
It must be possible to control serialization of fields or properties.

### PR DESCRIPTION
**Pull request by treblereel**

### CODE REVIEW

**Comment by treblereel** [comment]
@manstis may i ask you to take a look, i hope, this it what you need

**Comment by manstis** [comment]
Works great, thank-you @treblereel.

You'll need to format your code though; building locally I received this:
```
[ERROR] Found 1 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn com.coveo:fmt-maven-plugin:format"
[ERROR] Non complying file: /home/manstis/workspaces/git/manstis/forks/mapper-xml/tests/jre/src/test/java/org/treblereel/gwt/xml/mapper/client/tests/pmml/model/PMMLTest.java
```

**Comment by treblereel** [comment]
@manstis thanks! 

ok, i am merging it and releasing 0.3 to sonatype with current set of features

**Comment by manstis** [comment]
Don't forget to close https://issues.redhat.com/browse/KOGITO-5499!

**Pull request merged**
