### PR TITLE
KOGITO-5669: PMML generated model has case sensitive classes

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.redhat.com/browse/KOGITO-5669

@treblereel The second commit is the significant one for this PR.

When #90 is merged I'll rebase this one so it only includes the new PMML model (interfaces and classes).

I mentioned the other day that the PMML model you had in `jre-tests` was very old. This PR brings it bang up to date!

### CODE REVIEW

**Comment by manstis** [comment]
@treblereel This has been rebased now and only includes the PMML model changes.

As discussed I've also moved the mocked/stubbed `jaxb-api` interfaces/classes to the `common` module.

**Comment by manstis** [comment]
> @manstis 1071 new files, wow

Nope.. only 1,065 and they're not new as such but the "new" PMML model (replacing the old one you was using).

This "new" model is the beast that has been conjuring up the issues recently fixed.

**Comment by manstis** [comment]
Hi @treblereel I'm on vacation for a couple of weeks. It'd be nice if you're happy to merge this and release a new version of the plugin while I'm away :-)

**Comment by treblereel** [comment]
@manstis let me check it once again and i merge

**Pull request merged**
